# vim:ft=ansible:
---
- name: Installng build tools (gcc, make, ...)
  become: True
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - build-essential 
    - gcc
    - g++  
    - make
    - binutils
      
- name: install linux-headers
  become: True
  action: shell apt-get install -y linux-headers-$(uname -r)
  ignore_errors: True

- name: Installing git
  become: True
  package: name=zsh state=latest

- name: Installing git
  become: True
  package: name=git state=latest

- name: Installing vim
  become: True
  package: name=vim state=latest

- shell: vim +PluginInstall +qall

- name: Cloning  oh-my-zsh
  git:
     repo=https://github.com/robbyrussell/oh-my-zsh
     dest="~/.oh-my-zsh"

- name: Cloning Vundle
  git:
    repo=https://github.com/gmarik/Vundle.vim.git
    dest="~/.vim/bundle/Vundle.vim"

- name: Creating new ~/.zshrc
  copy:
    src="~/.oh-my-zsh/templates/zshrc.zsh-template"
    dest="~/.zshrc"

- name: Determining username
  action: shell whoami
  register: whoami
  sudo: False

- name: Changing the default shell to zsh
  action: user shell=/bin/zsh user={{whoami.stdout}}
  # action: shell chsh ec2-user -s /bin/zsh
  sudo: True
